image: gitpod/workspace-full-vnc
tasks:
  - init: sudo apt-get install python3-dialog -y
    command: python3 main.py
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - dracula-theme.theme-dracula